#!/bin/bash

diskused=$(df -h| grep  "/dev/sda1" |awk '{print $5}')

memfree=$(free -mh | grep Mem: | awk '{print $7}')

connections=$(netstat | grep tcp )

users=$( who |awk '{print $1}' )

echo -en  "This is a snapshot of your current system
              
              
              
              \e[36m    Disk used: $diskused
              \e[95m    Free memory:$memfree
              \e[31m     logged in Users:$ users     
              \e[46m
              
              open internet Connections:
              $connections
              
              
              \e[49m
              
